# Generated by Django 6.1.1 on 2026-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='service',
            field=models.CharField(choices=[('ai-machine-learning', 'AI and machine learning'), ('custom-software', 'Custom software'), ('web-applications', 'Web applications'), ('mobile-applications', 'Mobile applications'), ('business-automation', 'Business automation'), ('digital-platforms', 'Digital platforms'), ('other', 'Something else')], max_length=32),
        ),
    ]
